import {
  mdiAccount,
  mdiAccountGroupOutline,
  mdiAccountOutline,
  mdiAlertCircleOutline,
  mdiApps,
  mdiArrowLeft,
  mdiChevronLeft,
  mdiChevronRight,
  mdiCircleOutline,
  mdiClockOutline,
  mdiCogOutline,
  mdiDotsVertical,
  mdiDownload,
  mdiFileDocumentOutline,
  mdiGiftOutline,
  mdiHomeVariant,
  mdiHomeVariantOutline,
  mdiInformationOutline,
  mdiLinkVariant,
  mdiPaletteSwatchOutline,
  mdiShareVariantOutline,
  mdiTranslate,
  mdiUpdate,
} from '@mdi/js'
import type { IconAliases, IconSet } from 'vuetify'
import { VSvgIcon } from 'vuetify/components'

export const mdi: IconSet = {
  component: VSvgIcon,
}
export const aliases: IconAliases = {
  complete: undefined,
  cancel: undefined,
  close: undefined,
  delete: undefined,
  clear: undefined,
  success: undefined,
  info: mdiInformationOutline,
  warning: mdiAlertCircleOutline,
  error: mdiAlertCircleOutline,
  prev: mdiChevronLeft,
  next: mdiChevronRight,
  checkboxOn: undefined,
  checkboxOff: undefined,
  checkboxIndeterminate: undefined,
  delimiter: undefined,
  sortAsc: undefined,
  sortDesc: undefined,
  expand: undefined,
  menu: undefined,
  subgroup: undefined,
  dropdown: undefined,
  radioOn: undefined,
  radioOff: undefined,
  edit: undefined,
  ratingEmpty: undefined,
  ratingFull: undefined,
  ratingHalf: undefined,
  loading: undefined,
  first: undefined,
  last: undefined,
  unfold: undefined,
  file: undefined,
  plus: undefined,
  minus: undefined,
  calendar: undefined,
  back: mdiArrowLeft,
  share: mdiShareVariantOutline,
  openOthers: undefined,
  settings: mdiCogOutline,
  foh: mdiCircleOutline,
  more: mdiDotsVertical,
  link: mdiLinkVariant,
  clock: mdiClockOutline,
  home: mdiHomeVariantOutline,
  developer: mdiAccountOutline,
  navigation_home: mdiHomeVariantOutline,
  navigation_home_active: mdiHomeVariant,
  navigation_apps: mdiApps,
  navigation_apps_active: mdiApps,
  navigation_update: mdiUpdate,
  navigation_update_active: mdiUpdate,
  navigation_me: mdiAccountOutline,
  navigation_me_active: mdiAccount,
  iconButton_download: mdiDownload,
  setting_language: mdiTranslate,
  setting_design: mdiPaletteSwatchOutline,
  about_licenses: mdiFileDocumentOutline,
  about_donate: mdiGiftOutline,
  about_group: mdiAccountGroupOutline,
}
