/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./../../components/grid/AppContainer.vue')['default']
    AppDialog: typeof import('./../../components/dialog/AppDialog.vue')['default']
    AppList: typeof import('./../../components/list/AppList.vue')['default']
    AppListCategory: typeof import('./../../components/list/AppListCategory.vue')['default']
    AppListDialogItem: typeof import('./../../components/list/AppListDialogItem.vue')['default']
    AppListItem: typeof import('./../../components/list/AppListItem.vue')['default']
    AppListProjectItem: typeof import('./../../components/list/AppListProjectItem.vue')['default']
    AppListSingleSelectItem: typeof import('./../../components/list/AppListSingleSelectItem.vue')['default']
    AppPage: typeof import('./../../components/page/AppPage.vue')['default']
    AppRow: typeof import('./../../components/grid/AppRow.vue')['default']
    BackButton: typeof import('./../../components/appbar/BackButton.vue')['default']
    CenterSpace: typeof import('./../../components/CenterSpace.vue')['default']
    ContextMenu: typeof import('./../../components/app/ContextMenu.vue')['default']
    DialogActionsTemplate: typeof import('./../../components/dialog/DialogActionsTemplate.vue')['default']
    ErrorAlert: typeof import('./../../components/alert/ErrorAlert.vue')['default']
    NavigationDrawer: typeof import('./../../components/app/NavigationDrawer.vue')['default']
    PwaComponent: typeof import('./../../components/app/PwaComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemBar: typeof import('./../../components/app/SystemBar.vue')['default']
    TauriSystemBar: typeof import('./../../components/app/TauriSystemBar.vue')['default']
    UnsafeBypassAlert: typeof import('./../../components/alert/UnsafeBypassAlert.vue')['default']
    UnsafeBypassChromeGuide: typeof import('./../../components/guide/UnsafeBypassChromeGuide.vue')['default']
  }
}
